on:
  push:
    branches:
      - "master"
      - "vicky/gh-45"
name: "pre-release"
jobs:
  pre-release:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.5
    - name: "Checkout source code"
      uses: "actions/checkout@v2.3.4"
    - name: "Build for windows"
      run: go build -o . -v ./...
    - name: "release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          README.md
          spinup-host
